config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'plans/index'
  root to: "plans#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :plans
  resources :records
  resources :users, only: :show
  resources :spots

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/icon.rb
class Icon < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' , value: '---'},
    { id: 2, name: 'ホテル' , value: 'fa-bed'},
    { id: 3, name: 'お風呂' , value: 'fa-bath'},
    { id: 4, name: 'フード' , value: 'fa-burger'},
    { id: 5, name: 'レストラン' , value: 'fa-utensils'},
    { id: 6, name: 'ビュースポット' , value: 'fa-camera'},
    { id: 7, name: 'ショッピング' , value: 'fa-cart-shopping'},
    { id: 8, name: 'アクティビティ' , value: 'fa-person-biking'}
  ]

  include ActiveHash::Associations
  has_many :spots

end
 
  # <i class="fa-solid fa-bed"></i>ホテル
  # <i class="fa-solid fa-bath"></i>お風呂
  # <i class="fa-solid fa-burger"></i>フード
  # <i class="fa-solid fa-utensils"></i>レストラン
  # <i class="fa-solid fa-camera"></i>ビュースポット
  # <i class="fa-solid fa-cart-shopping"></i>ショッピング
  # <i class="fa-solid fa-person-biking"></i>アクティビティ

app/models/plan.rb
class Plan < ApplicationRecord
  validates :destination,    presence: true
  validates :text,           presence: true
  validates :prefecture_id,  presence: true
  validates :prefecture_id, numericality: { other_than: 1 , message: "can't be blank"}


  belongs_to :user
  has_one :record

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture


end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '---' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森' },
    { id: 4, name: '岩手' },
    { id: 5, name: '宮城' },
    { id: 6, name: '秋田' },
    { id: 7, name: '山形' },
    { id: 8, name: '福島' },
    { id: 9, name: '茨城' },
    { id: 10, name: '栃木' },
    { id: 11, name: '群馬' },
    { id: 12, name: '埼玉' },
    { id: 13, name: '千葉' },
    { id: 14, name: '東京' },
    { id: 15, name: '神奈川' },
    { id: 16, name: '新潟' },
    { id: 17, name: '富山' },
    { id: 18, name: '石川' },
    { id: 19, name: '福井' },
    { id: 20, name: '山梨' },
    { id: 21, name: '長野' },
    { id: 22, name: '岐阜' },
    { id: 23, name: '静岡' },
    { id: 24, name: '愛知' },
    { id: 25, name: '三重' },
    { id: 26, name: '滋賀' },
    { id: 27, name: '京都' },
    { id: 28, name: '大阪' },
    { id: 29, name: '兵庫' },
    { id: 30, name: '奈良' },
    { id: 31, name: '和歌山' },
    { id: 32, name: '鳥取' },
    { id: 33, name: '島根' },
    { id: 34, name: '岡山' },
    { id: 35, name: '広島' },
    { id: 36, name: '山口' },
    { id: 37, name: '徳島' },
    { id: 38, name: '香川' },
    { id: 39, name: '愛媛' },
    { id: 40, name: '高知' },
    { id: 41, name: '福岡' },
    { id: 42, name: '佐賀' },
    { id: 43, name: '長崎' },
    { id: 44, name: '熊本' },
    { id: 45, name: '大分' },
    { id: 46, name: '宮崎' },
    { id: 47, name: '鹿児島' },
    { id: 48, name: '沖縄' }

  ]

  include ActiveHash::Associations
  has_many :plans
  has_many :records
end

app/models/record.rb
class Record < ApplicationRecord
  validates :destination,    presence: true
  validates :text,           presence: true
  validates :prefecture_id,  presence: true
  validates :prefecture_id, numericality: { other_than: 1 , message: "can't be blank"}


  belongs_to :user
  belongs_to :plan, optional: true
  validate :validate_plan_presence, if: :plan_id?

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture

  private

  def validate_plan_presence
    unless Plan.exists?(id: plan_id)
      errors.add(:plan_id, "specified plan does not exist")
    end
  end
end

app/models/spot.rb
class Spot < ApplicationRecord
  validates :prefecture_id,  presence: true
  validates :icon_id, numericality: { other_than: 1 , message: "can't be blank"} 

  validates :spot_name,    presence: true
  validates :prefecture_id,  presence: true
  validates :prefecture_id, numericality: { other_than: 1 , message: "can't be blank"}


  belongs_to :user


  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :icon

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :plans 
  has_many :records 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    #sign_up（新規登録の処理）に対して、nicknameというキーのパラメーターを新たに許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
          #deviseでencrypted_passwordに登録する時ストロングパラメーターはこっちで書く→:password, :password_confirmation,
          #devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :password, :password_confirmation, :name, :profile, :occupation, :position])

  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :move_to_index, except: [:index] #追加

  def index
    @plans = Plan.order("created_at DESC") #変更要。start_dateにしたいけどそれだとstart_dateをnull:falseにしなければ

  end
def new
  @plan = Plan.new
  #  binding.pry

end
def create
  @plan = Plan.new(plan_params)
  # binding.pry
  if @plan.save
    redirect_to "/users/#{current_user.id}"
  else
    render "new", status: :unprocessable_entity
  end
end
def show
  @spot = Spot.new
  @plan = Plan.find(params[:id])
  @spots = Spot.where(user_id: @plan.user_id, prefecture_id: @plan.prefecture_id)
 
end
  private

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end
  def plan_params
    params.require(:plan).permit(:destination,:text,:prefecture_id,:city,:start_date,:end_date).merge(user_id: current_user.id)
  end

end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :move_to_index, except: [:index] #追加

  def index
    @records = Record.order("created_at DESC") #変更要。start_dateにしたいけどそれだとstart_dateをnull:falseにしなければ

  end
def new
  @record = Record.new
  #  binding.pry

end
def create
  @record = Record.new(record_params)
  # binding.pry
  if @record.save
    redirect_to "/users/#{current_user.id}"
  else
    render "new", status: :unprocessable_entity
  end
end

  private

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end
  def record_params
    params.require(:record).permit(:destination,:text,:prefecture_id,:city,:start_date,:end_date).merge(user_id: current_user.id)
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :move_to_index, except: [:index]

def new
  @spot = Spot.new
  #  binding.pry

end
def create
  @spot = Spot.new(spot_params)
  # binding.pry

  @plan = Plan.find(params[:plan_id]) #planのID
  @spots = Spot.where(user_id: @plan.user_id, prefecture_id: @plan.prefecture_id)

  # binding.pry
  if @spot.save
    redirect_to plan_path(@plan.id)
  else
    render "/plans/show", status: :unprocessable_entity
  end
end

  private

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end
  def spot_params
    params.require(:spot).permit(:icon_id,:spot_name,:information,:prefecture_id).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :move_to_index

  def show
    @nickname = current_user.nickname
    @user = User.find(params[:id])
    @plans = @user.plans
    @records = @user.records
  end

  private

  def move_to_index
    unless user_signed_in?
      redirect_to root_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>iscopy 旅を管理するアプリ</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <%# <link href="css/styles.css" rel="stylesheet" /> %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<script src="https://kit.fontawesome.com/81d6b0fe75.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <!-- Responsive navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container px-5">
            <%= link_to "iscopy", root_path, class: "navbar-brand" %>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link active", "aria-current" => "page" %></li>
                    <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">Contact</a></li>
                    <li class="nav-item"><a class="nav-link" href="#!">Services</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <%= yield %>


    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container px-5"><p class="m-0 text-center text-white">Copyright &copy; iscopy 2023</p></div>
    </footer>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <%# <script src="js/scripts.js"></script> %>
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <!-- * *                               SB Forms JS                               * *-->
    <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
    <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>

  </body>
</html>

app/views/plans/new.html.erb
<!-- Contact section-->
<section class="bg-light py-5">
    <div class="container px-5 my-5 px-5">
        <div class="text-center mb-5">
            <div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-envelope"></i></div>
            <h2 class="fw-bolder">新しい計画</h2>
            <p class="lead mb-0">行きたい場所や旅の目的を登録しよう</p>
        </div>
        <div class="row gx-5 justify-content-center">
            <div class="col-lg-6">
                <!-- * * * * * * * * * * * * * * *-->
                <!-- * * SB Forms Contact Form * *-->
                <!-- * * * * * * * * * * * * * * *-->
                <!-- This form is pre-integrated with SB Forms.-->
                <!-- To make this form functional, sign up at-->
                <!-- https://startbootstrap.com/solution/contact-forms-->
                <!-- to get an API token!-->
                <%= form_with model: @plan, local: true do |f| %>
                <%# <form id="contactForm" data-sb-form-api-token="API_TOKEN"> %>
                    <%= render 'shared/error_messages', model: f.object %>
                    <!-- Name input-->
                    <div class="form-floating mb-3">
                        <%= f.text_field :destination, class:"form-control", id:"destination", type:"text", placeholder:"目的地（必須）" %>
                        <%# <input class="form-control" id="destination" type="text" placeholder="旅の目的地..." data-sb-validations="required" /> %>
                        <label for="destination">目的地（必須）</label>
                        <div class="invalid-feedback" data-sb-feedback="name:required">目的地を入力してください</div>
                    </div>
                    <!-- Email address input-->
                    <div class="form-floating mb-3">
                        <%= f.text_field :text, class:"form-control", id:"text", type:"text", placeholder:"北海道でスカイダイビング" , style:"height: 10rem"%>
                        <%# <textarea class="form-control" id="text" type="text" placeholder="北海道でスカイダイビング" data-sb-validations="required" style="height: 10rem"></textarea> %>
                        <label for="text">行きたい場所や旅の目的（必須）</label>
                        <div class="invalid-feedback" data-sb-feedback="email:required">テキストを入力してください</div>
                    </div>
                    <!-- Phone number input-->
                    <div class="form-floating mb-3">
                        <%# <input class="form-control" id="prefecture_id" type="number" placeholder="北海道" data-sb-validations="required" /> %>
                        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"form-control"}) %>
                        <label for="prefecture_id">都道府県（必須）</label>
                        <div class="invalid-feedback" data-sb-feedback="prefecture_id:required">都道府県を選択してください</div>
                    </div>
                    <!-- Message input-->
                    <div class="form-floating mb-3">
                        <%= f.text_field :city, class:"form-control", id:"city", type:"text", placeholder:"市町村..." %>
                        <%# <input class="form-control" id="city" type="text" placeholder="市町村..."/> %>
                        <label for="city">市町村</label>
                    </div>
                    <!-- Message input-->
                    <div class="form-floating mb-3">
                        <%= f.text_field :start_date, class:"form-control", id:"start_date", type:"date", placeholder:"2023/10/1" %>
                        <%# <input class="form-control" id="start_date" type="date" placeholder="2023/10/1" data-sb-validations="date"/> %>
                        <label for="start_date">開始日</label>
                        <div class="invalid-feedback" data-sb-feedback="date:date">Date is not valid.</div>
                    </div>
                    <!-- Message input-->
                    <div class="form-floating mb-3">
                        <%= f.text_field :end_date, class:"form-control", id:"end_date", type:"date", placeholder:"2023/10/7" %>
                        <%# <input class="form-control" id="end_date" type="date" placeholder="2023/10/7" data-sb-validations="date"/> %>
                        <label for="end_date">終了日</label>
                        <div class="invalid-feedback" data-sb-feedback="date:date">Date is not valid.</div>
                    </div>
                    <!-- Submit success message-->
                    <!---->
                    <!-- This is what your users will see when the form-->
                    <!-- has successfully submitted-->
                    <div class="d-none" id="submitSuccessMessage">
                        <div class="text-center mb-3">
                            <div class="fw-bolder">Form submission successful!</div>
                            To activate this form, sign up at
                            <br />
                            <a href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                        </div>
                    </div>
                    <!-- Submit error message-->
                    <!---->
                    <!-- This is what your users will see when there is-->
                    <!-- an error submitting the form-->
                    <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                    <!-- Submit Button-->
                    <div class="d-grid">
                            <%= f.submit "Submit", class:"btn btn-primary btn-lg"%>
                      <%# <button class="btn btn-primary btn-lg disabled" id="submitButton" type="submit">Submit</button> %>
                    </div>
                <%# </form> %>
              <% end %>
            </div>
        </div>
        
    </div>
</section>

app/views/plans/show.html.erb
        <!-- Header-->
        <header class="py-5">
            <div class="container px-lg-5">
                <div class="p-4 p-lg-5 bg-light rounded-3 text-left">
                    <div class="m-4 m-lg-5">
                        <h1 class="display-6 fw-bold"><%= @plan.prefecture.name%><%= @plan.city%>への旅</h1>
                        <p class="fs-4"><%= @plan.start_date%>～<%= @plan.end_date%></p>
                        <h5 class="display-8 fw-bold">目的地：<%= @plan.destination%></h5>
                        <p class="fs-8">行きたい場所や旅の目的：<%= @plan.text%></p>
                        <a class="btn btn-primary btn-lg" href="#!">編集する</a>
                        <a class="btn btn-secondary btn-lg" href="#!">削除</a>
                    </div>
                </div>
            </div>
        </header>
        <!-- Page Content-->
        <section class="pt-4">
            <div class="container px-lg-5">
            <!-- Page Features-->
                <div class="row gx-lg-5">
                    <% @spots.each do |spot|%>
                    <div class="col-md-4 mb-5">
                        <div class="card bg-light  h-100">
                            <div class="card-body">
                                <div class="feature bg-primary bg-gradient text-white rounded-3 mb-4 mt-n4"><i class="fa-solid <%=spot.icon.value%>"></i></div>
                                <h2 class="card-title"><%= spot.spot_name%></h2>
                                <%# <h4 class="card-title"><%= spot.spot_name%></h4>
                                <p class="card-text"><%= spot.information%></p>
                                <%# <h2 class="fs-4 fw-bold">Fresh new layout</h2> %>
                                <%# <p class="mb-0">With Bootstrap 5, we've created a fresh new layout for this template!</p> %>
                            </div>
                        </div>
                    </div>
                    <%end%>
                    <div class="row gx-lg-5">
                    <div class="col-lg-6 col-xxl-4 mb-5">
                      <div class="card h-100">
                        <div class="card-body text-center p-4 p-lg-5 pt-0 pt-lg-0">
                        <h2 class="fs-4 fw-bold"><%=@plan.prefecture.name%>の新しいスポットを登録</h2>
                        <%= form_with model: @spot, local: true do |f| %>
                        <%= render 'shared/error_messages', model: f.object%>
                        <!-- Phone number input-->
                        <div class="form-floating mb-3">
                            <%= f.collection_select(:icon_id, Icon.all, :id, :name, {}, {class:"form-control"}) %>
                            <label for="icon_id">種類（必須）</label>
                            <div class="invalid-feedback" data-sb-feedback="icon_id:required">種類を選択してください</div>
                        </div>
                        <!-- Name input-->
                        <div class="form-floating mb-3">
                            <%= f.text_field :spot_name, class:"form-control", id:"spot_name", type:"text", placeholder:"別府温泉" %>
                            <label for="spot_name">スポット名（必須）</label>
                            <div class="invalid-feedback" data-sb-feedback="name:required">スポット名を入力してください</div>
                        </div>
                        <!-- Information input-->
                        <div class="form-floating mb-3">
                            <%= f.text_field :information, class:"form-control", id:"information", type:"text", placeholder:"有名な温泉" , style:"height: 10rem"%>
                            <label for="information">情報</label>
                        </div>
                        <!-- Phone number input-->
                        <%# <div class="form-floating mb-3"> %>
                            <%# <%= f.text_field :prefecture_id, class:"form-control", id:"prefecture_id", type:"text", value:@plan.prefecture.name %>
                            <%# <label for="prefecture_id">都道府県</label> %>
                        <%= f.hidden_field :prefecture_id, value: @plan.prefecture_id, id:"prefecture_id" %>
                        <%# </div> %>
                        <input value=<%=@plan.id%> name='plan_id' type="hidden">
                        <!-- Submit success message-->
                        <!---->
                        <!-- This is what your users will see when the form-->
                        <!-- has successfully submitted-->
                        <div class="d-none" id="submitSuccessMessage">
                            <div class="text-center mb-3">
                                <div class="fw-bolder">Form submission successful!</div>
                            </div>
                        </div>
                        <!-- Submit error message-->
                        <!---->
                        <!-- This is what your users will see when there is-->
                        <!-- an error submitting the form-->
                        <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                        <!-- Submit Button-->
                        <div class="d-grid">
                                <%= f.submit "Submit", class:"btn btn-primary btn-lg" %>
                        </div>
                    <%# </form> %>
                  <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/users/show.html.erb
        <!-- Page Content-->
        <div class="container px-4 px-lg-5">
            <!-- Heading Row-->
            <div class="row gx-4 gx-lg-5 align-items-center my-5">
                <div class="col-lg-7"><img class="img-fluid rounded mb-4 mb-lg-0" src="/assets/chizu_color.png" alt="..." /></div>
                <div class="col-lg-5">
                    <h1 class="font-weight-light"><%= @nickname %>さんの旅 マイページ</h1>
                    <p>This is a template that is great for small businesses. It doesn't have too much fancy flare to it, but it makes a great use of the standard Bootstrap core components. Feel free to use this template for any project you want!</p>
                    <%= link_to "計画を登録する!", new_plan_path, class:"btn btn-primary" %>
                    <%= link_to "計画のない旅を記録する!", new_record_path, class:"btn btn-primary" %>
                </div>
            </div>
            <!-- Call to Action-->
            <div class="card text-white bg-secondary my-5 py-4 text-center">
                <div class="card-body"><p class="text-white m-0">計画や記録を登録するには地図をクリック！</p></div>
            </div>
            <!-- Content Row-->
            <div class="row gx-4 gx-lg-5">

                <h3 class="font-weight-light">計画中</h3>
                <% @plans.each do |plan|%>
                    <div class="col-md-4 mb-5">
                        <div class="card h-100">
                            <div class="card-body">
                                <h2 class="card-title"><%= plan.prefecture.name%></h2>
                                <h4 class="card-title"><%= plan.destination%></h4>
                                <p class="card-text"><%= plan.text%></p>
                                <%# textは先頭の140文字くらいを表示 %>
                            </div>
                            <div class="card-footer"><%=link_to "More Info", plan_path(plan.id), class:"btn btn-primary btn-sm"%></div>
                            <%# <a class="btn btn-primary btn-sm" href="#!">More Info</a></div> %>
                        </div>
                    </div>
                <%end%>
                <%# 3件くらい表示してmoreとかview allにしたい %>
                <%# 計画がない時にダミーカードを表示したい %>

                <h3 class="font-weight-light">旅の記録</h3>
                <% @records.each do |record|%>
                    <div class="col-md-4 mb-5">
                        <div class="card h-100">
                            <div class="card-body">
                                <h2 class="card-title"><%= record.prefecture.name%></h2>
                                <h4 class="card-title"><%= record.destination%></h4>
                                <p class="card-text"><%= record.text%></p>
                                <%# textは先頭の140文字くらいを表示 %>
                            </div>
                            <div class="card-footer"><a class="btn btn-primary btn-sm" href="#!">More Info</a></div>
                        </div>
                    </div>
                <%end%>
                <%# 3件くらい表示してmoreとかview allにしたい %>
                <%# 記録がない時にダミーカードを表示したい %>

            </div>
        </div>